// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOtLZ5F57lUN1RsGY05SWPoTWbVCoP0ww',
    appId: '1:610083134108:web:318331816b2eb35d192b59',
    messagingSenderId: '610083134108',
    projectId: 'belajarbersama-54559',
    authDomain: 'belajarbersama-54559.firebaseapp.com',
    databaseURL: 'https://belajarbersama-54559-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarbersama-54559.firebasestorage.app',
    measurementId: 'G-CQ33E3WQQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmXxV6Z6pz5HRJn6uesAafz7Afg9rR9V8',
    appId: '1:610083134108:android:1bc4f1b95ffdb356192b59',
    messagingSenderId: '610083134108',
    projectId: 'belajarbersama-54559',
    databaseURL: 'https://belajarbersama-54559-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarbersama-54559.firebasestorage.app',
  );
}
